### ISSUE TITLE
Unable to scroll with keycluster trackball when using trackpoint

### ISSUE THREAD

**Issue by provinzio** [kareltucek/firmware#102]
When I use the trackpoint module to move the mouse I can not use the trackball on the keycluster module to scroll.

I use the newest version 8.10.12.kt.3.

This is no problem with the "normal" firmware 8.10.12.

My `$onInit` macro does not effect the outcome of the issue. 

```
$set module.trackpoint.navigationMode.mod cursor
$set module.trackpoint.navigationMode.fn cursor
$set module.trackpoint.navigationMode.mouse cursor

$set module.keycluster.navigationMode.mod scroll
$set module.keycluster.navigationMode.fn scroll
$set module.keycluster.navigationMode.mouse scroll
```

**Comment by kareltucek** [comment]
Thanks for report!

Fixed in https://github.com/kareltucek/firmware/releases/tag/v8.10.12.kt.4 .
