### ISSUE TITLE
Getting Started Link-Reference in README incorrect

### ISSUE THREAD

**Issue by provinzio** [kareltucek/firmware#103]
Hey @kareltucek,

I saw that you freshen up the README and that the link to the `Getting started` might point to the wrong file. I believe it should go to this page https://github.com/kareltucek/firmware/blob/master/doc-dev/user-guide.md .

my branch : https://github.com/provinzio/firmware/tree/fix-readme-getting-started-reference
my fix commit: https://github.com/kareltucek/firmware/compare/master...provinzio:firmware:fix-readme-getting-started-reference

Signing the CLA to open a PR didn't seem reasonable for this.

**Comment by kareltucek** [comment]
Good catch, thanks!
