### ISSUE TITLE
Using a keymapping that uses control leaves control activated

### ISSUE THREAD

**Issue by VinceG3** [kareltucek/firmware#32]
Version 8.5.4 of the official firmware fixed an issue where:

- Make the modifiers of shortcut keys stick only as long as the layer switcher key of a shortcut key is being held.

However this version of the firmware still exhibits the issue. To reproduce, remap a Base layer key to control anything, it most annoys me in a browser, so try control-w for close tab. Close a tab with the remapped key, then click on any link. It will control-click the link. The held state can be cleared up by tapping Mod.

Note that remapping on the Mod layer doesn't cause the problem, as releasing Mod clears up the held state before you have a chance to click anything. If you remap Mod-W to Control-W, then holding Mod down, tapping W then clicking a button after releasing W but before releasing Mod will Control-Click. 

I have reproduced the behavior with Alt and Super Base layer remappings.

Flashing back to latest vanilla fixes it, while flashing back to 8.5.3 brings back the issue.

**Comment by kareltucek** [comment]
Thanks for report, will look into it soon! Unless you need sticky modifiers, you should be able to disable them entirely by $setStickyModsEnabled 0.

**Comment by VinceG3** [comment]
Setting Sticky Mods off got rid of the behavior for me, thanks! Didn't realize that was a feature people actually needed, curious what it's used for.

**Comment by kareltucek** [comment]
It's for windows's alt+tab, but the proper behaviour should definitely be that of the official 8.5.4 ;-).

**Comment by kareltucek** [comment]
Fixed. Thanks for the catch!
