### ISSUE TITLE
Mapping shift/nonshift scancodes independently doesn't work with secondary shift

### ISSUE THREAD

**Issue by WindChimeRan** [kareltucek/firmware#58]
Mapping shift/nonshift scancodes independently:

$ifShift suppressMods write 4
$ifNotShift write %

With a _primary_ shift pressed, it works fine. But with a _primary_ ( _secondary_ shift, it will output % when holding it.

**Comment by WindChimeRan** [comment]
problem solved! The language you designed is super powerful!
```
$ifKeyActive 27 final tapKey 4
$ifKeyActive 85 final tapKey 4
$write %
```

**Comment by kareltucek** [comment]
I am happy you have found a workaround to solve your problem, but the reported behaviour is indeed strange and should be fixed or at least investigated. Therefore, please lets leave the ticket open - I definitely do indend to look into it, just have not found the time yet. 

Also sorry for no reply - I definitely did not indent to ignore it like this...

**Comment by kterui9019** [comment]
Hello, thanks for providing us with a great tool.
The solution to use `ifKeyActive` will not work `suppressMods`.
```
$ifKeyActive 29 final suppressMods tapKey [
```
expect: `[`
actual : `{`

I specified noOp, as in https://github.com/kareltucek/firmware/issues/41, but it did not work.

**Comment by kareltucek** [comment]
Should be fixed in next release.
