### ISSUE TITLE
Double click detection erratic

### ISSUE THREAD

**Issue by Greenactivist** [kareltucek/firmware#69]
The following macro is meant to send a code to my window manager (stumpwm) that should make it open a specific appication when the when the key is double clicked and otherwise make it act as a super kay:

$holdKey leftGui
$ifNotDoubletap break
LCtrl+LShift+LSuper+H

However double tap detection seems quite erratic.  Sometimes I need to do it two or three times before it has any effect.

**Comment by kareltucek** [comment]
Terribly sorry for so late reply!

Is it possible that you simply don't tap the keys fast enough?

**Comment by kareltucek** [comment]
Alternatively, is it possible that your window manager ignores too short taps? (Can you reproduce it with two regular keys in a text editor?)

**Comment by Greenactivist** [comment]
Thanks for your reply. It seems to be that I was not tapping the keys fast enough.  I have more or less got the knack of doing it now and now it almost always works.   So the issue can be closed.

Incidentally, I find the macros really useful,  I can now enter Chinese punctuation and the 20 most common characters easily from the keyboard.  Of course I have to use the standard input method for the others but what I have done really speeds things up.

**Comment by kareltucek** [comment]
> It seems to be that I was not tapping the keys fast enough. I have more or less got the knack of doing it now and now it almost always works. So the issue can be closed.

Still, this is valuable feedback. The timer speed actually seems to change depending on various factors, and I have to admit that with my current build the real timeout is too short for me too. 

I think it might be a good idea to either finetune it or make it configurable.

**Comment by kareltucek** [comment]
I have increased the timeout to 400 and added `doubletapDelay` configuration option. Not sure when I will roll out next release though...

**Comment by Greenactivist** [comment]
Sounds like a good idea.  Maybe at some  time in the future the timeout could be configurable in the agent,
