### ISSUE TITLE
autoshift

### ISSUE THREAD

**Issue by swerter** [kareltucek/firmware#70]
Hi there

I've recently borrowed a keyboardio atreus and they have this nice firmware-plugin https://github.com/keyboardio/Kaleidoscope/tree/master/plugins/Kaleidoscope-AutoShift
Would it be complicated to implement this with these macros? Any suggestions or hints?

Thanks.

**Comment by kareltucek** [comment]
Hi!

I think this should suffice:

```
delayUntilReleaseMax 350
ifPlaytime 350 final tapKey S
tapKey s
```

**Comment by swerter** [comment]
thanks a lot for your help.
