### ISSUE TITLE
Persistent registers

### ISSUE THREAD

**Issue by soraxas** [kareltucek/firmware#91]
Would there be a possibility for introducing registers that are persistent across reboots?

For example, if I have a register that saves the current selected LED dim level (some sort of round-robin macro-key that changes register level), it would much nicer if I can set that register to store its value on disk. However, this would require using part of the current storage for persistent register storage.

**Comment by kareltucek** [comment]
At the moment, the firmware never writes into the EEPROM on its own. From my side, keeping things this ways is a part of being confident that my firmware is safe to use and being able to guarantee it. (I.e, that it will not brick any device by wearing out the EEPROM.) 

In theory it is possible, and the eeprom is expected to withstand quite a lot. Also, there has already been discussion about remembering state of backlight across reboots in the official repository. 

In any case, this (i.e., general support for persistent state) should be mainly discussed and coordinated with Laszlo in the official github. 

(Closing, but feel free to follow up.)
