### ISSUE TITLE
Scrolling and Trackball can't work at the same time.

### ISSUE THREAD

**Issue by mrpond** [kareltucek/firmware#94]
Install the latest Agent:
Agent version: 1.5.17
Use Agent to update to the latest firmware:
Right keyboard half firmware: 8.10.12
Left keyboard half firmware: 8.10.12
Key cluster firmware: 8.10.12
Trackball firmware: 8.10.123.

refer to this issue:
https://github.com/UltimateHackingKeyboard/firmware/issues/452

after apply set module.trackball.navigationMode.mod cursor

While scrolling with left module I can't move UHK's trackball cursor.

**Comment by kareltucek** [comment]
In which scenarios you need to scroll and move cursor at the same time?

**Comment by kareltucek** [comment]
But yes, this is a relevant ticket. Only one navigation mode can currently be active at a time, meaning that only one of them is actually applied if both are used at the same time.

(This can be fixed.)

**Comment by mrpond** [comment]
> In which scenarios you need to scroll and move cursor at the same time?

a lot, it like when you want to click some link on the lower zone of screen.
I usually scroll the page up, so I save trackball moving.

**Comment by mondalaci** [comment]
We've just received a report of this issue, so I'm attaching a 9.0.0 pre-release including this fix: 
[uhk-firmware-9.0.0-df83a18.tar.gz](https://github.com/kareltucek/firmware/files/8153164/uhk-firmware-9.0.0-df83a18.tar.gz)

**Comment by mrpond** [comment]
> We've just received a report of this issue, so I'm attaching a 9.0.0 pre-release including this fix: [uhk-firmware-9.0.0-df83a18.tar.gz](https://github.com/kareltucek/firmware/files/8153164/uhk-firmware-9.0.0-df83a18.tar.gz)

I go test it for you.. ^^

update:  working scroll and trackball work at the same time now.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/18654771/156898822-6b2caffc-9ea2-4980-922e-ee7e3678efde.png">

**Comment by mondalaci** [comment]
@kareltucek Feel free to close this issue then. I don't have permission, so I can't :)

**Comment by kareltucek** [comment]
@mondalaci I know, I intended to close it when I get to publish a release.

**Comment by kareltucek** [comment]
Done
